# Generated by Django 2.2.6 on 2019-10-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='content',
            new_name='tasklistId',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='title',
        ),
    ]
