# Generated by Django 2.2.6 on 2019-10-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0003_auto_20191010_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasklistTasklist',
        ),
        migrations.AlterModelTable(
            name='tasklist',
            table='tasklist',
        ),
    ]
