# Generated by Django 2.2.6 on 2019-10-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0004_auto_20191010_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Replyattachdocument',
        ),
        migrations.DeleteModel(
            name='Reportlist',
        ),
        migrations.DeleteModel(
            name='Taskattachdocument',
        ),
        migrations.DeleteModel(
            name='tasklist',
        ),
        migrations.DeleteModel(
            name='Weeklyreportlist',
        ),
    ]
