# Generated by Django 2.2.6 on 2019-12-12 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0006_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_commen'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='project',
        ),
    ]
