# Generated by Django 2.2.6 on 2019-12-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0007_auto_20191212_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(db_column='projectId', primary_key=True, serialize=False)),
                ('projectname', models.CharField(db_column='projectName', max_length=100)),
                ('projectdescription', models.CharField(blank=True, db_column='projectDescription', max_length=3000, null=True)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
