# Generated by Django 2.2.6 on 2019-12-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0008_auto_20191212_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachDocument',
            fields=[
                ('task_attach_document_id', models.AutoField(db_column='task_Attach_Document_Id', primary_key=True, serialize=False)),
                ('attach_document', models.CharField(db_column='attach_Document', max_length=100)),
                ('uploaded_date', models.DateTimeField(db_column='uploaded_Date')),
            ],
            options={
                'db_table': 'task_attach_document',
                'managed': False,
            },
        ),
    ]
