# Generated by Django 2.2.6 on 2020-02-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0009_taskattachdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(db_column='semester_id', primary_key=True, serialize=False)),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], db_column='semester', max_length=17)),
                ('start_date', models.DateTimeField(db_column='start_Date')),
            ],
        ),
    ]
