# Generated by Django 2.2.6 on 2020-02-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0010_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'managed': False},
        ),
    ]
