# Generated by Django 2.2.6 on 2020-02-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0011_auto_20200212_2158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='semester',
            table='semester_start_date',
        ),
    ]
